package com.bitla.ts.domain.pojo.available_routes

data class AvailableRoutesModelItem(
    val arr_time: String,
    val available_seats: Int,
    val boarding_point_details: List<BoardingPointDetail>,
    val boarding_point_ids: String,
    val bus_type: String,
    val bus_type_id: Int,
    val cancellation_policy: List<CancellationPolicy>,
    val commission: String,
    val dep_time: String,
    val destination: String,
    val destination_id: Int,
    val discount_percentage: Int,
    val discounted_price: Int,
    val drop_off_details: List<DropOffDetail>,
    val dropoff_point_ids: String,
    val duration: String,
    val fare_str: String,
    val fare_string: Int,
    val id: Int,
    val is_apply_bp_dp_fare: Boolean,
    val is_cancellable: String,
    val is_service_blocked: Boolean,
    val is_service_tax_applicable: Boolean,
    val last_boarding_stage_time: String,
    val name: String,
    val number: String,
    val origin: String,
    val origin_id: Int,
    val reservation_id: Long,
    val social_distancing_guaranteed: Boolean,
    val status: String,
    val total_seats: Int,
    val via: List<String>
)