package com.bitla.ts.domain.pojo.confirm_pay_at_bus

data class PayAtBusResponse(
    val age: Int,
    val arr_date: String,
    val arr_time: String,
    val barcode_value: String,
    val bluetooth_print_template: String,
    val boarding_details: BoardingDetails,
    val booking_source: String,
    val bus_type: String,
    val cancellation_policies: List<CancellationPolicy>,
    val coach_number: String,
    val convenience_charge_amount: Int,
    val custom_print_ticket: String,
    val date_format: String,
    val dep_time: String,
    val destination: String,
    val destination_id: Int,
    val discount_category: Any,
    val drop_off_details: DropOffDetails,
    val duration: String,
    val insurance_trans_details: InsuranceTransDetails,
    val is_allow_cancellation_type_as_fixed_or_percentage: Boolean,
    val is_allow_to_alter_cancel_percent: Boolean,
    val is_allow_to_print_barcode: Boolean,
    val is_confirm_ota_booking: Boolean,
    val is_coupon_created_ticket: Boolean,
    val is_coupon_used: Boolean,
    val is_e_phone_booking: Boolean,
    val is_eticket: Boolean,
    val is_onbehalf_online_ticket: Boolean,
    val is_partial_cancelled: Boolean,
    val is_pay_at_bus_ticket: Boolean,
    val is_reprint_check: Boolean,
    val is_update_ticket: Boolean,
    val is_used_prepost_open_ticket: Boolean,
    val is_zero_percent_cancellation: Boolean,
    val mobile_terms_and_conditions: String,
    val no_of_seats: Int,
    val onbehalf_of_booked_by_user_or_agent: String,
    val origin: String,
    val origin_id: Int,
    val passenger_details: List<PassengerDetail>,
    val policy_remarks: String,
    val policy_status: String,
    val remarks: String,
    val reservation_id: Long,
    val round_trip_number: Any,
    val seat_numbers: String,
    val service_number: String,
    val service_requests: ServiceRequests,
    val service_tax_amount: Int,
    val sharing_pdf_link: String,
    val sms_ticket_hash: String,
    val terminal_ref_no: String,
    val ticket_fare: Int,
    val ticket_lead_detail: TicketLeadDetail,
    val ticket_number: String,
    val ticket_status: String? = null,
    val total_fare: Int,
    val travel_date: String,
    val ts_app_print_template: String,
    val response: Response

)

data class Response(
    val code: String,
    val message: String
)