package com.bitla.ts.domain.pojo.BpDpService.response

data class PassengerDetail(
    val age: Int,
    val agent_ref_number: Any,
    val basic_amount: Double,
    val boarding_address: String,
    val boarding_at: String,
    val boarding_at_id: Int,
    val boarding_landmark: String,
    val booked_by: String,
    val booked_by_login: String,
    val booking_type_id: Int,
    val bording_date_time: String,
    val bp_stage_latitude: String,
    val bp_stage_longitude: String,
    val commission_amount: Double,
    val destination: String,
    val dp_stage_latitude: String,
    val dp_stage_longitude: String,
    val drop_off: String,
    val dropoff_id: Int,
    val email: String,
    val id_card: IdCard,
    val is_boarded: Int,
    val is_coupon_created_ticket: Boolean,
    val is_primary: Int,
    val is_shifted: Boolean,
    val is_ticket_confirm: Boolean,
    val is_trackingo_sms_allowed: Boolean,
    val mobile: String,
    val name: String? = null,
    val net_amount: Double,
    val origin: String,
    val pnr_number: String,
    val seat_number: String? = null,
    val service_tax_amount: Double,
    var status: Int,
    val temperature: String,
    val title: String,
    val transaction_charges: Double,
    var switch: Boolean = false
)