package com.bitla.ts.domain.pojo.privilege_details_model.response.child_model


import com.google.gson.annotations.SerializedName

data class PassengerConfigs(
    @SerializedName("ALTERNATE_EMAIL")
    val aLTERNATEEMAIL: ALTERNATEEMAILX,
    @SerializedName("BLOOD_GROUP")
    val bLOODGROUP: BLOODGROUPX,
    @SerializedName("BOARDING_STAGE_ADDRESS")
    val bOARDINGSTAGEADDRESS: BOARDINGSTAGEADDRESSX,
    @SerializedName("BOARDING_STAGE_LANDMARK")
    val bOARDINGSTAGELANDMARK: BOARDINGSTAGELANDMARKX,
    @SerializedName("DEFAULT_ID_TYPE")
    val dEFAULTIDTYPE: DEFAULTIDTYPE,
    @SerializedName("DESTINATION_ADDRESS")
    val dESTINATIONADDRESS: DESTINATIONADDRESSX,
    @SerializedName("DROP_OFF_STAGE_ADDRESS")
    val dROPOFFSTAGEADDRESS: DROPOFFSTAGEADDRESSX,
    @SerializedName("DROP_OFF_STAGE_LANDMARK")
    val dROPOFFSTAGELANDMARK: DROPOFFSTAGELANDMARKX,
    @SerializedName("FIRST_NAME")
    val fIRSTNAME: FIRSTNAMEX,
    @SerializedName("LAST_NAME")
    val lASTNAME: LASTNAMEX,
    @SerializedName("ORIGIN_ADDRESS")
    val oRIGINADDRESS: ORIGINADDRESSX,
    @SerializedName("PASSENGER_ADDRESS")
    val pASSENGERADDRESS: PASSENGERADDRESS,
    @SerializedName("PASSENGER_AGE")
    val pASSENGERAGE: PASSENGERAGE,
    @SerializedName("PASSENGER_ALTERNATE_NO")
    val pASSENGERALTERNATENO: PASSENGERALTERNATENO,
    @SerializedName("PASSENGER_BOARDING_STAGE")
    val pASSENGERBOARDINGSTAGE: PASSENGERBOARDINGSTAGE,
    @SerializedName("PASSENGER_DOB")
    val pASSENGERDOB: PASSENGERDOB,
    @SerializedName("PASSENGER_DROP_OFF_STAGE")
    val pASSENGERDROPOFFSTAGE: PASSENGERDROPOFFSTAGE,
    @SerializedName("PASSENGER_DUAL_FARE_TYPE")
    val pASSENGERDUALFARETYPE: PASSENGERDUALFARETYPE,
    @SerializedName("PASSENGER_EMAIL")
    val pASSENGEREMAIL: PASSENGEREMAIL,
    @SerializedName("PASSENGER_ID_NUMBER")
    val pASSENGERIDNUMBER: PASSENGERIDNUMBER,
    @SerializedName("PASSENGER_ID_TYPE")
    val pASSENGERIDTYPE: PASSENGERIDTYPE,
    @SerializedName("PASSENGER_NAME")
    val pASSENGERNAME: PASSENGERNAME,
    @SerializedName("PASSENGER_NATIONALITY")
    val pASSENGERNATIONALITY: PASSENGERNATIONALITYX,
    @SerializedName("PASSENGER_PHONE")
    val pASSENGERPHONE: PASSENGERPHONE,
    @SerializedName("PASSENGER_REMARKS")
    val pASSENGERREMARKS: PASSENGERREMARKS,
    @SerializedName("PASSENGER_TITLE")
    val pASSENGERTITLE: PASSENGERTITLE,
    @SerializedName("PRIMARY_PASSENGER_MANDATORY")
    val pRIMARYPASSENGERMANDATORY: PRIMARYPASSENGERMANDATORYX
)