package com.bitla.ts.domain.pojo.view_reservation

import com.google.gson.annotations.SerializedName

data class PassengerDetailX(
    val actual_travel_date: String?,
    val boarding_city: String?,
    val booked_by: String?,
    val booking_type: String?,
    val destination: Int?,
    val dropping_city: String?,
    val dropping_point: String?,
    val dropping_point_date: String?,
    val dropping_point_time: String?,
    val dropping_stage_name: String?,
    val gst_amount: Double?,
    val id_card: IdCardX?,
    val is_phone_booking: Boolean?,
    val landmark: String?,
    val onbehalf_travel_branch_id: Int?,
    val origin: Int?,
    val passenger_age: Int?,
    val passenger_name: String?,
    val pnr_number: String?,
    val phone_number: String?,
    val remarks: String?,
    val seat_number: String?,
    val sex: String?,
    val stage_dep_time: String?,
    val stage_name: String?,
    val status: Int?,
    val temperature: String?,
    val ticket_fare: Double?,
    val total_trip: Int?,
    val is_meal: Boolean?,
    val trip_counts: Int?,
    var terminal_ref_no: String? = "",
    var age: String? = "",
)