package com.bitla.ts.domain.pojo.multistation_data

import java.io.Serializable

data class PassengerDetail(
    val previous_shift_numbers: String = "",
    val name: String = "",
    val age: Int? = null,
    val gender: String = "",
    val origin_id: Int? = null,
    val origin_name: String = "",
    val destination_id: Int? = null,
    val destination_name: String = "",
    val from_to: String = "",
    val blocking_time: Any?,
    val seat_fare: String = "",
    val ticket_no: String = "",
    val release_datetime: String = "",
    val booking_fare: String = "",
    val phone_num: String = "",
    val boarding_stage: String = "",
    val landmark: String = "",
    val drop_off_stage: String = "",
    val seat_no: String = "",
    val shifted_by: String = "",
    val shifted_on: String = "",
    val booked_by: String = "",
    val remarks: String = "",
    val can_cancel: Boolean,
    val can_cancel_ticket_for_user: Boolean,
    val can_shift_ticket: Boolean,
    val is_update_ticket: Boolean,
    val is_phone_block: Boolean,
    val no_of_seats: Int = 0,
    val seat_numbers: String = "",
    val dep_time: String = "",
    val travel_date: String = "",
    val booked_date: String = "",
    val status: Int? = null,
    val is_his_booking: Boolean,
    val booked_by_id: Int? = null,
    val travel_branch_id: Int? = null,
    val issued_by: String = "",
    val issued_by_contact_no: String = "",
    var is_selected: Boolean = false,
    var can_confirm_phone_block: Boolean = false,
    var can_release_phone_block: Boolean = false,
    val policy_number: String? = "",
    var is_temporary_phone_block: Boolean? = null,
    var online_agent: String? = "",
    var onbehalf: String? = "",
    var pay_mode: String? = ""
) : Serializable
